### ISSUE TITLE
Discovery modules as "services"

### ISSUE THREAD

**Issue by nunofmn** [libp2p/interface-peer-discovery#1]
As discussed in https://github.com/libp2p/js-libp2p/issues/49 with @diasdavid, there is the need for an interface for peer discovery.

An example of loading a discovery module into libp2p is in https://github.com/ipfs/js-libp2p-ipfs-nodejs/blob/master/src/index.js#L36-L38

The actual discovery interface doesn't allow to explicitly start the discovery process, so it starts when the discovery module object is initialized.

This is a problem since the discovery process will be launched before the libp2p node is started, and therefore will not be possible to interact with the discovered peers (for example, do peer verification).

One possible approach is consider discovery modules as services, by adding a `start()`and `stop()` methods to their interface.

Thoughts?

**Comment by daviddias** [comment]
`start` and `stop` sounds like a good approach. I know you started working in the refactor, could you post here the links to the PR?

Thanks @nunofmn :)
